#!/usr/bin/env python3

import sys
import json
from subprocess import check_call

def main():
    if len(sys.argv) < 2:
        print('Usage: foreach COMMAND...')
        exit(2)

    with open('vss-extension.json') as f:
        for dir in json.load(f)['files']:
            check_call(sys.argv[1:], cwd=dir['path'])

if __name__ == '__main__':
    main()
