trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: ./make.py build
  displayName: Building tasks
- bash: npm i mocha -g
  displayName: Install mocha
- bash: npm i -g tfx-cli
  displayName: Install tfx CLI
- bash: ./make.py test
  displayName: Run tests
- powershell: |
    $res = tfx extension create --manifest-globs ./vss-extension.json --json | ConvertFrom-Json
    cp $res.path $(Build.ArtifactStagingDirectory)
  displayName: 'Creating extension package'
- publish: $(Build.ArtifactStagingDirectory)
  artifact: extension
  displayName: 'Publish extension file to ADO pipeline storage'
