trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: ./foreach yarn install --non-interactive
  displayName: Installing dependencies
- bash: ./foreach yarn tsc
  displayName: Compile typescript
- bash: npm i mocha -g
  displayName: Install mocha
- bash: npm i -g tfx-cli
  displayName: Install tfx CLI
- bash: ./foreach mocha tests/_suite.js
  displayName: Run tests
- powershell: |
    $res = tfx extension create --manifest-globs ./vss-extension.json --json | ConvertFrom-Json
    cp $res.path $(Build.ArtifactStagingDirectory)
  displayName: 'Creating extension package'
- publish: $(Build.ArtifactStagingDirectory)
  artifact: extension
  displayName: 'Publish extension file to ADO pipeline storage'
